name: Cloud Docker Image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ['release']

jobs:
  build-cloud:
    runs-on: ubuntu-latest
    name: Build Cloud
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Login to container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u maxs-rose --password-stdin
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Move Docker file
        run: |
          mv docker/cloud.Dockerfile Dockerfile
          rm -rf docker
      - name: Build
        run: |
          docker build . -t env-tree
      - name: Publish
        run: |
          docker image tag env-tree ghcr.io/maxs-rose/env-tree:latest
          docker push ghcr.io/maxs-rose/env-tree:latest